### ISSUE TITLE
Hello, can I use this utility for selenium? 

### ISSUE THREAD

**Issue by KalvinThien** [fingerprintjs/fingerprintjs-pro-chrome-extension-example#32]
Hello, can I use this utility for selenium? I plan to use it to automatically post videos on TikTok, if I use it, can I hide the Fingerprint Browser from being detected by Tiktok on the same device?
Please answer my questions above, thank you

**Comment by JuroUhlar** [comment]
Hi, no, this extension example does not hide anything. It helps you (as an owner of a Chrome extension) to identify the users of your extension using Fingerprint Pro.
